(
                 '@serverId',
                 '@gameId',
                 @gameClubId,
                 '@gameName',
                 @mType,
                 '@imagePath',
                 '@imageName',
                 @active,
                 '@localizationCode',
                 '@categoryIdList',
                 @sort,
                 'MT',
                 5
                )