INSERT INTO[dbo].[T_WebSite_Game_MappingInfo] (
                [gameId],
                [code],
                [gameName],
                [class],
                [active],
                [supportWeb],
                [supportMobile],
                [localizationCode],
                [thirdPartyId],
                [gameType],
                [serverId],
                [gameClubId],
                [imagePath],
                [imageName],
                [categoryIdList],
                [sort]
                )
                VALUES