(
                 '@gameId',
                 '@code',
                 '@gameName',
                 '@class',
                 @active,
                 @supportWeb,
                 @supportMobile,
                 '@localizationCode',
                 'RCG',
                 1,
                 '',
                 0,
                 '',
                 '',
                 '',
                 0
                )