                (
                 '@serverId',
                 '@gameId',
                 @gameClubId,
                 '@gameName',
                 '@imagePath',
                 '@imageName',
                 @active,
                 '@localizationCode',
                 '@categoryIdList',
                 @sort,
                 @gameType,
                 '@thirdPartyId',
                 @mType,
                 @gType
                )